apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-sops-secret
spec:
    secretTemplates:
        - name: postgres-secret
          stringData:
            username: ENC[AES256_GCM,data:vHEhigcI1XjLbw0Q3nMv1A==,iv:pUJqYAUtDBUNYaYcoM9DGiE6kGYE8RJTir83/WyjTL8=,tag:ENkLVzGyX9+TFWOyn+6sBA==,type:str]
            password: ENC[AES256_GCM,data:3B+HtADGvaafzUjWETQ=,iv:Hbse1r/sYGShL3NCCSggxxig4DPoIGkc9m0MSvnylSU=,tag:Zs9y4VnxfcSw85xBamh3Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYW9WeE96RUlBdFI4c0Zp
            ckpabE9jQzJMd3U1NTUyaC9ReGcwdTRGaVFnCjBDUnNzTkUzYzViL011Z0tob2VP
            U3JoTmc2d0VFVTFZNTRJdHFZTEJDUzgKLS0tIHF4dmNXZVZNdnQ4bm53NC9QWDE5
            emJwK1FmRnJNZ3N6VjkwZm9VNEp3ZlkKkmZJHlLX8CyTLEU1BhYSgYvaLQCixFi8
            d6KOsnRTkxeGXCjA56PodS+pCH4wQnvkojXFEFCtUrIEORJRukwpTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T09:38:00Z"
    mac: ENC[AES256_GCM,data:0OupITyG3oLShDloDI+F6/uidd91KPcje60wQQDaNqt1m3JDSQZ4n9g4sWzWlycFZQsgBJb6jz00Te8PJqgZlhE2ML+vSmmNQVZnCIah4zhC8WzF8sMTNQ/f3ZUFWfgf6WLzBibNTD7znonUzVKKf40eYIyFCEONNoiBRv0CsPY=,iv:tBP+QnlLlVVQzjKsVW83LMckL491QA77kSMIk78j8Ek=,tag:uhZcgQq8HyR0w0QrDspZ2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
