apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres-sops-secret
spec:
    secretTemplates:
        - name: postgres-secret
          stringData:
            password: ENC[AES256_GCM,data:jy6T01T1OqFZLUWTdzU=,iv:2msjQ2YwIv/OosfvJl0t6Ku5xiBxNegndv0ALme4fGk=,tag:gKz78BU4shWUq4mX3yeS7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZzVHY2RqZHZtQ1hpQXpk
            eW5kc1ZMdWUxUzRVQXBoc0wwQ1Vlbms5Um5BCmFUNGlyTDN0R2Z0Sk00T0QwWEE1
            VFpVZnZhSVR1YnhTa2trekFVUlppQlkKLS0tIDU2anllQlc4M2J4ZVc2L0FVOTRO
            U3VqWHp1aTBKVEhaUFU2TFIyN0p5U0EK83Nn5Fa+vcbwZl0V/8ODx+YiNIoBCyea
            Sw65dgV/OvyWtwQZqVCnomVlQaBMZ6V/WCruJ3W3PIbf4ITp6eamRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-28T09:23:48Z"
    mac: ENC[AES256_GCM,data:bMlZDhK9SOOl/WE+XTsI0PWFBMXrZVhYhceV7JDkQjRDOMaDNtM8RE1xrsYDRE71ew9m9PybL3AovpwsQjFTjHaeBRsm7tzcfjQr1FS5kg6VYlIHpCo+VxxXibBNsJgCmfOhO8WFQ8FLmU4Ntdyr0POq5sZ2bkop8eRWq1v5DCY=,iv:sosCR0jTuFrk9YEtn4nQLMbgS3RUMfL0LxWSMAgY7D4=,tag:qkbluQfkfRVn6T239noNrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
